### ISSUE TITLE
Fresh .NET Core 6 project

### ISSUE THREAD

**Issue by StrayerJ** [quicksln/LiteDB.Identity#7]
Is there any documentation/demo on how to get this to work, if possible, with a fresh Core 6 MVC/Razor web project?  Things seem to differ a bit from previous versions.

![image](https://user-images.githubusercontent.com/45401423/216627387-704a027b-d608-42cf-a3ad-bd51d0ccc85c.png)

**Comment by quicksln** [comment]
I believe the issue is due to the usage of 'IdentityUser' instead of 'LiteDbUser' somewhere in your application. Please begin your inspection from the '_LoginPartial.cshtml' file and make the necessary replacements.

Replace 
```
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
```
With 

```
@inject SignInManager<LiteDB.Identity.Models.LiteDbUser> SignInManager
@inject UserManager<LiteDB.Identity.Models.LiteDbUser> UserManager
```

I’ve also updated project references to the latest **LiteDB 5.0.15** and Identity Stores 6.0.13 for **.NET 6** on GitHub and released a new Nuget Package https://www.nuget.org/packages/LiteDB.Identity

Or install it :
`Install-Package LiteDB.Identity -Version 1.0.6`

**Comment by quicksln** [comment]
I have attached an updated configuration for .NET 6 and a sample project below. I hope you find it helpful and that it enables you to quickly start with LiteDB and LiteDB Identity :) 

[WebApplication1.zip](https://github.com/quicksln/LiteDB.Identity/files/10668870/WebApplication1.zip)

![image](https://user-images.githubusercontent.com/65227444/217076745-7618164d-2dda-4178-b757-af9f3c80402d.png)

**Comment by StrayerJ** [comment]
Thank a ton! I'll check it out.
